kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc
  namespace: nfs-client
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
